repos:
  - repo: local
    hooks:
      - id: ty-check
        name: ty type check
        entry: uvx --refresh ty check
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-check
        name: ruff linter
        entry: uvx --refresh ruff check
        language: system
        types: [python]
        pass_filenames: true

      - id: no-ignore-comments
        name: check for ignore comments
        entry: bash scripts/check-ignore-comments.sh
        language: system
        types: [python]
        pass_filenames: true
