name: "Set Pending Status for Manual Workflows [auto]"
# This workflow sets placeholder statuses for manual workflows when a pull
# request is opened, reopened, or synchronized. The placeholder statuses
# are updated when those workflows are run manually.
permissions:
  contents: read
  statuses: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ 'main' ]

jobs:
  set-pending-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set placeholder status checks
        uses: ./.github/actions/set-pending-status
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: "Docker Pipeline Test (Docker, Self-hosted)"
          workflow-file: "pipeline_test_self_hosted_docker.yml"
          description: "Docker pipeline test workflow not yet run"

      - name: Set placeholder status check for Docker tests (self-hosted)
        uses: ./.github/actions/set-pending-status
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: "Tests (Docker, Self-hosted)"
          workflow-file: "tests_self_hosted_docker.yml"
          description: "Docker tests (self-hosted) workflow not yet run"

      - name: Set placeholder status check for Docker tests
        uses: ./.github/actions/set-pending-status
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: "Tests (Docker)"
          workflow-file: "tests_docker.yml"
          description: "Docker tests workflow not yet run"
